<style>
    .use-default {
        display: none;
    }
</style>
<?php $scope = $this->helper('Trustpilot\Reviews\Helper\Data')->getScope() ?>
<?php $storeId = $this->helper('Trustpilot\Reviews\Helper\Data')->getWebsiteOrStoreId() ?>
<script>
    const ajaxUrl = "<?php echo $this->getUrl('trustpilot_reviews') ?>";
    const scope = "<?php echo $scope ?>";
    const scopeId = "<?php echo $storeId ?>";
    const trustBoxPreviewUrl = '<?php echo \Trustpilot\Reviews\Model\Config::TRUSTPILOT_TRUSTBOX_PREVIEW_URL ?>';
</script>
<script type="text/javascript">
    function onTrustpilotIframeLoad() {
        if (typeof sendSettings === "function" && typeof sendPastOrdersInfo === "function") {
            sendSettings();
            sendPastOrdersInfo();
        } else {
            window.addEventListener('load', function () {
                sendSettings();
                sendPastOrdersInfo();
            });
        }
    }
</script>
<div tabindex="0">
    <iframe
        src='<?php echo $this->getIntegrationAppUrl(); ?>'
        id="configuration_iframe"
        frameborder="0"
        scrolling="no"
        width="100%"
        height="1400px"
        data-plugin-version='<?php echo \Trustpilot\Reviews\Model\Config::TRUSTPILOT_PLUGIN_VERSION ?>'
        data-source='Magento2'
        data-version='<?php echo 'Magento2-'. $this->getVersion(); ?>'
        data-page-urls='<?php echo $this->getPageUrls($scope, $storeId); ?>'
        data-transfer='<?php echo $this->getIntegrationAppUrl(); ?>'
        data-past-orders='<?php echo $this->getPastOrdersInfo($scope, $storeId); ?>'
        data-settings='<?php echo $this->getSettings($scope, $storeId); ?>'
        data-product-identification-options = '<?php echo $this->getProductIdentificationOptions(); ?>'
        data-is-from-marketplace='<?php echo \Trustpilot\Reviews\Model\Config::TRUSTPILOT_IS_FROM_MARKETPLACE ?>'
        data-configuration-scope-tree = '<?php echo $this->getStoreInformation(); ?>'
        data-plugin-status = '<?php echo $this->getPluginStatus($scope, $storeId); ?>'
        onload="onTrustpilotIframeLoad();"
    >
    </iframe>
   <div id='trustpilot-trustbox-preview'
        hidden='true'
        data-page-urls='<?php echo $this->getPageUrls($scope, $storeId); ?>'
        data-custom-trustboxes='<?php echo $this->getCustomTrustBoxes($scope, $storeId); ?>'
        data-settings='<?php echo $this->getSettings($scope, $storeId); ?>'
        data-source='Magento2'
        data-sku="<?php echo $this->getSku($scope, $storeId); ?>"
        data-name="<?php echo $this->getProductName($scope, $storeId); ?>"
   >
   </div>
</div>

<script type="text/javascript" async>
    require(['<?php echo \Trustpilot\Reviews\Model\Config::TRUSTPILOT_TRUSTBOX_PREVIEW_URL ?>']);
</script>
