<?php /* @var $block \Trustpilot\Reviews\Block\Head */?>
<script type="text/javascript">

	(function(w,d,s,r,n){w.TrustpilotObject=n;w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)};
	a=d.createElement(s);a.async=1;a.src=r;a.type='text/java'+s;f=d.getElementsByTagName(s)[0];
	f.parentNode.insertBefore(a,f)})(window,document,'script', '<?php echo $block->getScriptUrl(); ?>', 'tp');
	tp('register','<?php echo $block->getInstallationKey(); ?>');
</script>
<?php if ($block->getTrustBoxStatus() === 'enabled'): ?>
	<script type="text/javascript" src="<?php echo $block->getWgxpathUrl(); ?>"></script>
	<script type="text/javascript"> wgxpath.install(); </script>

	<script type="text/javascript" src="<?php echo $block->getWidgetScriptUrl(); ?>" async></script>	
<?php else: ?>
	<script type="text/javascript">
		if (window.self !== window.top) {
			var s = document.createElement("script");
			s.type = "text/javascript";
			s.src = "<?php echo $this->getWidgetScriptUrl(); ?>";
			s.async = true;
			document.head.append(s);
		}
	</script>
<?php endif; ?>
